# Generated by Django 3.2.9 on 2021-11-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_owner_name', models.CharField(default='', max_length=100)),
                ('parcel_mail_address', models.TextField(default='')),
                ('parcel_land_value', models.FloatField(default='')),
                ('parcel_land_sq_ft', models.FloatField(default='')),
                ('parcel_polygon_string_list', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('incident_latitude', models.FloatField(default=0.0)),
                ('incident_longitude', models.FloatField(default=0.0)),
                ('incident_address_string', models.CharField(default='', max_length=200)),
                ('incident_type', models.CharField(default='', max_length=100)),
                ('incident_sub_type', models.CharField(default='', max_length=100)),
                ('incident_day_of_week', models.CharField(default='', max_length=8)),
                ('incident_event_opened', models.DateTimeField(default='')),
                ('incident_event_closed', models.DateTimeField(default='')),
                ('incident_response_zone', models.CharField(default='', max_length=10)),
                ('incident_units_involved', models.CharField(default='', max_length=200)),
                ('incident_weather_description', models.TextField(default='')),
                ('incident_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.parcel')),
            ],
        ),
    ]
